flowable:
  databaseSchemaUpdate : true #create-drop create false
  cmmn.enabled : true
  dmn.enabled : true
  form.enabled : true
  databaseSchema : liansen_flow

logging:
  name: flow-service
    
---

#生产环境
spring.profiles: service-pro

  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8084

spring:
  profiles:
    include: service-pro
  datasource:
    url : jdbc:mysql://localhost:3306/liansen_flow?useUnicode=true&characterEncoding=UTF-8
    username : root
    password: root
  