logging:
  name: identity-service
     
     
---

#生产环境
spring.profiles: service-pro
  
  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8082

spring:
  profiles:
    include: service-pro
  datasource:
    url : jdbc:mysql://localhost:3306/plumdo_identity?useUnicode=true&characterEncoding=UTF-8
    username : root
#    password : kyb123456
    password : 123456
  