logging:
  name: form-service
     
     
---

#生产环境
spring.profiles: service-pro
  
  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8083


spring:
  profiles:
    include: service-pro
  datasource:
    url : jdbc:mysql://localhost:3306/liansen_form?useUnicode=true&characterEncoding=UTF-8
    username : root
    password: root
  